import { jsPDF } from "jspdf";
import { Project } from "../types";

export interface PdfExportOptions {
  format: "a4" | "letter";
  orientation: "portrait" | "landscape";
  quality: "Standard" | "High Quality" | "Print Quality";
  includeOriginalThumbnails: boolean;
  includeTableOfContents: boolean;
  includeQuizzes: boolean;
}

export function generateNotebookPdf(
  project: Project,
  options: PdfExportOptions = {
    format: "a4",
    orientation: "portrait",
    quality: "High Quality",
    includeOriginalThumbnails: false,
    includeTableOfContents: true,
    includeQuizzes: true,
  }
) {
  const doc = new jsPDF({
    format: options.format,
    orientation: options.orientation,
    unit: "mm",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = margin;

  function checkPageBreak(neededHeight: number) {
    if (cursorY + neededHeight > pageHeight - margin - 10) {
      doc.addPage();
      cursorY = margin;
      drawHeaderFooter();
    }
  }

  function drawHeaderFooter() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 150);

    // Header
    doc.text(
      `AI Smart Notebook | ${project.title.slice(0, 45)}`,
      margin,
      10
    );
    doc.text(
      project.subject,
      pageWidth - margin,
      10,
      { align: "right" }
    );
    doc.setDrawColor(225, 228, 235);
    doc.setLineWidth(0.3);
    doc.line(margin, 12, pageWidth - margin, 12);

    // Footer
    const pageNum = doc.getNumberOfPages();
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
    doc.text(
      "Generated by AI Smart Notebook",
      margin,
      pageHeight - 8
    );
    doc.text(
      `Page ${pageNum}`,
      pageWidth - margin,
      pageHeight - 8,
      { align: "right" }
    );
  }

  // --- 1. COVER PAGE ---
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Decorative border
  doc.setDrawColor(79, 70, 229);
  doc.setLineWidth(1.5);
  doc.rect(margin, margin, pageWidth - margin * 2, pageHeight - margin * 2);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(15, 23, 42);
  doc.text(project.title, pageWidth / 2, 70, { align: "center", maxWidth: contentWidth - 20 });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(79, 70, 229);
  doc.text(`Subject: ${project.subject}`, pageWidth / 2, 90, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Template Style: ${project.styleTemplate}  •  ${project.pages.length} Pages Digitized`,
    pageWidth / 2,
    100,
    { align: "center" }
  );

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, 115, pageWidth / 2 + 40, 115);

  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(
    project.description || "Clean, structured academic notes transcribed from handwritten material.",
    pageWidth / 2,
    130,
    { align: "center", maxWidth: contentWidth - 30 }
  );

  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Export Date: ${new Date().toLocaleDateString()} | Verified Accuracy`,
    pageWidth / 2,
    pageHeight - 35,
    { align: "center" }
  );

  // --- 2. TABLE OF CONTENTS ---
  if (options.includeTableOfContents && project.chapters.length > 0) {
    doc.addPage();
    cursorY = 25;
    drawHeaderFooter();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42);
    doc.text("Table of Contents", margin, cursorY);
    cursorY += 12;

    project.chapters.forEach((chap, idx) => {
      checkPageBreak(12);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      doc.text(`Chapter ${chap.number}: ${chap.title}`, margin, cursorY);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 116, 139);
      doc.text(`Pages: ${chap.pageIds.length}`, pageWidth - margin, cursorY, { align: "right" });

      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.2);
      doc.line(margin, cursorY + 2, pageWidth - margin, cursorY + 2);
      cursorY += 9;
    });

    cursorY += 10;
  }

  // --- 3. CHAPTERS & PAGES CONTENT ---
  project.pages.forEach((page) => {
    doc.addPage();
    cursorY = 22;
    drawHeaderFooter();

    // Page badge
    doc.setFillColor(238, 242, 255);
    doc.roundedRect(margin, cursorY, 32, 6, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(67, 56, 202);
    doc.text(`PAGE ${page.pageNumber}`, margin + 16, cursorY + 4.2, { align: "center" });

    // Topic & Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(page.notes.title || page.topic, margin, cursorY + 14, { maxWidth: contentWidth });
    cursorY += 22;

    // Subtopics
    if (page.notes.subtopics.length > 0) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(`Topics: ${page.notes.subtopics.join(" • ")}`, margin, cursorY);
      cursorY += 8;
    }

    // Important Points Section
    if (page.notes.importantPoints.length > 0) {
      checkPageBreak(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      doc.text("Important Points", margin, cursorY);
      cursorY += 6;

      page.notes.importantPoints.forEach((pt) => {
        checkPageBreak(12);
        // Importance dot
        const colorMap: Record<string, [number, number, number]> = {
          HIGH: [220, 38, 38],
          MEDIUM: [217, 119, 6],
          LOW: [5, 150, 105],
        };
        const dotColor = colorMap[pt.importance] || [79, 70, 229];
        doc.setFillColor(dotColor[0], dotColor[1], dotColor[2]);
        doc.circle(margin + 2, cursorY - 1.5, 1.2, "F");

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(51, 65, 85);
        const lines = doc.splitTextToSize(`[${pt.importance}] ${pt.text}`, contentWidth - 8);
        doc.text(lines, margin + 6, cursorY);
        cursorY += lines.length * 4.5 + 2;
      });
      cursorY += 4;
    }

    // Definitions
    if (page.notes.definitions.length > 0) {
      checkPageBreak(20);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      doc.text("Definitions", margin, cursorY);
      cursorY += 6;

      page.notes.definitions.forEach((d) => {
        checkPageBreak(12);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(15, 23, 42);
        doc.text(`• ${d.term}: `, margin + 2, cursorY);
        const termWidth = doc.getTextWidth(`• ${d.term}: `);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(71, 85, 105);
        const defLines = doc.splitTextToSize(d.definition, contentWidth - termWidth - 4);
        doc.text(defLines, margin + 2 + termWidth, cursorY);
        cursorY += defLines.length * 4.5 + 2;
      });
      cursorY += 4;
    }

    // Formulas
    if (page.notes.formulas.length > 0) {
      checkPageBreak(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      doc.text("Formulas & Mathematical Relations", margin, cursorY);
      cursorY += 6;

      page.notes.formulas.forEach((f) => {
        checkPageBreak(16);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, cursorY - 3, contentWidth, 12, 2, 2, "F");
        doc.setDrawColor(226, 232, 240);
        doc.roundedRect(margin, cursorY - 3, contentWidth, 12, 2, 2, "S");

        doc.setFont("courier", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(30, 58, 138);
        doc.text(f.clean || f.original, margin + 4, cursorY + 2);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text(f.explanation, margin + 4, cursorY + 7);
        cursorY += 16;
      });
      cursorY += 4;
    }

    // Code Blocks
    if (page.notes.codeBlocks.length > 0) {
      page.notes.codeBlocks.forEach((cb) => {
        checkPageBreak(35);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10.5);
        doc.setTextColor(30, 41, 59);
        doc.text(`Code Block (${cb.language.toUpperCase()})`, margin, cursorY);
        cursorY += 5;

        const codeLines = doc.splitTextToSize(cb.code, contentWidth - 8);
        const boxHeight = codeLines.length * 4.2 + 8;
        checkPageBreak(boxHeight + 5);

        doc.setFillColor(15, 23, 42);
        doc.roundedRect(margin, cursorY - 2, contentWidth, boxHeight, 2, 2, "F");

        doc.setFont("courier", "normal");
        doc.setFontSize(8);
        doc.setTextColor(226, 232, 240);
        doc.text(codeLines, margin + 4, cursorY + 3);
        cursorY += boxHeight + 4;
      });
    }

    // Summary & Key Takeaways
    if (page.notes.summary) {
      checkPageBreak(20);
      doc.setFillColor(240, 253, 244);
      doc.roundedRect(margin, cursorY, contentWidth, 14, 2, 2, "F");
      doc.setDrawColor(187, 247, 208);
      doc.roundedRect(margin, cursorY, contentWidth, 14, 2, 2, "S");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(22, 101, 52);
      doc.text("PAGE SUMMARY:", margin + 4, cursorY + 5);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(21, 128, 61);
      const sumLines = doc.splitTextToSize(page.notes.summary, contentWidth - 8);
      doc.text(sumLines, margin + 4, cursorY + 10);
      cursorY += 18;
    }
  });

  // Save/trigger download
  const safeTitle = project.title.toLowerCase().replace(/[^a-z0-9]/g, "_") || "notebook";
  doc.save(`${safeTitle}_digital_notebook.pdf`);
}
